name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: maven

    - name: Build
      run: mvn -B package

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: quetoo-installer-small
        path: target/quetoo-installer-small.jar
